default: &default
  adapter: postgresql
  host: 82.29.155.181
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: tfguser
  password: <%= ENV['PG_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: tfg_development
  # database: storage/development.sqlite3

test:
  <<: *default
  database: tfg_test
  # database: storage/test.sqlite3

production:
  <<: *default
  database: tfg_production
  # url: <%#= ENV["DATABASE_URL"] %>
  # database: path/to/persistent/storage/production.sqlite3
